--- #YAML:1.0
name:                AppConfig
version:             1.66
abstract:            AppConfig is a bundle of Perl5 modules for reading configuration files and parsing command line arguments.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Wardley <abw@wardley.org>
